pipeline {
    agent any

    environment {
        IMAGE_NAME = "devops-test-app"
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('app') {
                    sh 'docker build -t $IMAGE_NAME:$BUILD_NUMBER .'
                }
            }
        }

        stage('Run Container') {
            steps {
                sh 'docker run -d -p 5001:5000 $IMAGE_NAME:$BUILD_NUMBER'
            }
        }

    }

    post {
        success {
            echo 'Build Successful 🚀'
        }
        failure {
            echo 'Build Failed ❌'
        }
    }
}
